### PR TITLE
CLN-4360 Enable storage deploy action to upload only to blob storage

### PR DESCRIPTION
**Pull request by mplesec**
https://leanix.atlassian.net/browse/CLN-4360

Adding this option since deploying with `LeanIX SaaS Intelligence` subscription should not upload to file storage, only blob storage. Throws [this error](https://github.com/Cleanshelf/squrb-v2/runs/4163151202?check_suite_focus=true) otherwise.

### CODE REVIEW

**Comment by konstantintieber** [comment]
I do not have access to Cleanshelf repositories. Could you please copy the error into this PR?

Also I think you'd need to adapt `backupDeployedVersion` as well to not backup on azure file storage when the `version-deployment` parameter is `true`

**Comment by konstantintieber** [comment]
Also: whenever changing something in this project, you need to run the `update-dist.sh` script.

**Comment by mplesec** [comment]
The error:
```
Now deploying to Azure File Storage siwesteuropetest.
/home/runner/work/squrb-v2/squrb-v2/azcopy copy ./frontoffice/storybook-static/* https://siwesteuropetest.file.core.windows.net/k8s-cdn-proxy/squrb-v2-si-storybook?se=2021-11-10T11%3A19%3A11Z&sp=rwac&spr=https&sv=2018-03-28&ss=f&srt=o&sig=YX80F8Oz0%2BZSONyyl%2BMK8NNkOismTYmS7%2BYaNYKh/EA%3D --exclude-path index.html;main.js;polyfills.js;polyfills-es5.js;styles.css;scripts.js;logout.html --recursive=true --overwrite=true
INFO: Scanning...
INFO: Any empty folders will be processed, because source and destination both support folders

Job 12f8ac53-f3d0-1c42-6024-7f0831085946 has started
Log file is located at: /home/runner/.azcopy/12f8ac53-f3d0-1c42-6024-7f0831085946.log


100.0 %, 0 Done, 0 Failed, 0 Pending, 0 Skipped, 0 Total (scanning...), 
INFO: Trying 4 concurrent connections (initial starting point)          
100.0 %, 0 Done, 0 Failed, 0 Pending, 0 Skipped, 0 Total (scanning...), 


Job 12f8ac53-f3d0-1c42-6024-7f0831085946 summary
Elapsed Time (Minutes): 0.0334
Number of File Transfers: 39
Number of Folder Property Transfers: 2
Total Number of Transfers: 41
Number of Transfers Completed: 0
Number of Transfers Failed: 41
Number of Transfers Skipped: 0
TotalBytesTransferred: 0
Final Job Status: Failed

Error: The process '/home/runner/work/squrb-v2/squrb-v2/azcopy' failed with exit code 1
```

**Review by yae-leanix — CHANGES_REQUESTED** [review]
Please also update the `action.yml` file to reflect the new input (https://github.com/leanix/storage-deploy-action/blob/master/action.yml). 

I could imagine that it now makes sense to create separate functions to deploy to blob storage or file share. I think carrying the parameter through the functions to make an early return is a suboptimal solution.

**Comment by konstantintieber** [comment]
I wonder why this error occurs. Aren't your storage containers setup in the same way as the ones we use for the LeanIX frontend? In this case they should have both blob and file storage.
As far as I know this is ensured by setting `cdn` to `true` in the infrastructure-service-environment config: https://github.com/leanix/infrastructure-service-environment/blob/master/service-environments/pathfinder-web-integration-hub.yaml

**Comment by mplesec** [comment]
@konstantintieber According to @daniellohausenleanix: "It fails as it tries to deploy to the k8s-cdn-proxy file share which not exists in the SI Subscription as it is not needed for SMP."

**Comment by konstantintieber** [comment]
@mplesec I guess you meant to ping @dan-leanix.

@dan-leanix can you please tell me why SMP is using Azure Blob Storage and not Azure File Storage? As I understand we had availability issues when serving Azure Blob Storage behind the cdn-proxy an that's why we switched to Azure File Storage.
Is the SMP team not affected here?

Should the LeanIX frontends also switch to Azure Blob Storage only again?

**Comment by dan-leanix** [comment]
@konstantintieber SMP does not use the CDN-Proxy. The frontend is served directly from their separate Azure CDN with the Azure Storage as the backend. Hence, they only need to deploy to blob storage and do not need the additional file storage deployment which is required for the EAM/VSM frontends.

**Comment by konstantintieber** [comment]
@dan-leanix thanks for the swift reply 🚀

**Review by konstantintieber — APPROVED** [review]
It would be nice to extend the existing test workflow with a test that validates that when `only-deploy-blob` is `true` that nothing is uploaded to azure file storage.

This can be done in a follow up PR.

**Review by yae-leanix — APPROVED** [review]

**Pull request merged**
