### PR TITLE
INVT-9468 Re-add Versioning

### PR DESCRIPTION
**Pull request by yae-leanix**
This reverts commit 88c2d8743904f60cba7747cbb0c6a3ac5acaf099 and readds versioning.

### CODE REVIEW

**Comment by yae-leanix** [comment]
@superquadratic Because of the tagging strategy which is mandatory for the way we keep track of releases, it will be necessary to pass the current branch name as input to the action. From the pipelines that I know from our monorepo this will most likely not be a problem to supply, but still requires me to adapt all of our GitHub workflows in pathfinder-web.

Another possibility that I can think of is to make the versioning optional. But this makes the action more complicated, which might be unnecessary considering the use case of this action.

I'll prepare a PR and then we might decide if we want our pipelines to pass the branch name as input to this action.

(cc @konstantintieber)

**Comment by superquadratic** [comment]
Passing the branch name as a parameter sounds like a small price to pay if we can get by without a working copy then (side note: is it not possible to access the [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) from the action and use the `ref` from there?).

Please keep in mind that it the new parameter is mandatory, we not only need to update all uses of this action in the pathfinder-web repo, but in all our repos, e.g. also all the reports that are deployed to CDN.

To simplify this in the future, I've been wanting to plant this idea for quite some time now (also for @perbernhardt 😉 ): If we switched from using this and other actions as `storage-deploy-action@master` to `storage-deploy-action@v1` (like the "official" ones), we could add a new mandatory parameter like this in the future without having to adapt all the workflows. It would rather be "opt-in" by updating the version. Keep in mind that we wouldn't have to increase the version for every change, only the "breaking" ones – `v1` would be a branch, not a tag. We could also treat older versions as "deprecated", but as long as they keep running fine, why require the update?

**Comment by perbernhardt** [comment]
> Passing the branch name as a parameter sounds like a small price to pay if we can get by without a working copy then (side note: is it not possible to access the [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) from the action and use the `ref` from there?).
> 
> Please keep in mind that it the new parameter is mandatory, we not only need to update all uses of this action in the pathfinder-web repo, but in all our repos, e.g. also all the reports that are deployed to CDN.
> 
> To simplify this in the future, I've been wanting to plant this idea for quite some time now (also for @perbernhardt 😉 ): If we switched from using this and other actions as `storage-deploy-action@master` to `storage-deploy-action@v1` (like the "official" ones), we could add a new mandatory parameter like this in the future without having to adapt all the workflows. It would rather be "opt-in" by updating the version. Keep in mind that we wouldn't have to increase the version for every change, only the "breaking" ones – `v1` would be a branch, not a tag. We could also treat older versions as "deprecated", but as long as they keep running fine, why require the update?

I would highly recommend that we manage to handle this WITHOUT a new mandatory parameter. I am not sure if I really get the problem already but we could do something like "if I have not everything in place to do versioning/rollbacks (e.g. a checkout OR a given branch parameter), then I don't do versioning/rollbacks. This way also everyone can step by step "opt in " to using rollbacks.
Otherwise, as Guido rightly says, we need to introduce "versions" on the action, although I would highly recommend to not do something like "v1, v2, v3" but instead just do what I like to call a "breaking change handshake":
- Introduce a feature branch on the action that introduces the breaking change
- Switch all clients to that version, e.g. "storage-deploy-action@feature-branch-123" step by step, adhering to the breaking change (e.g. introducing the parameter)
- If all clients are migrated, merge the branch to master
- Switch all clients back to master step by step
This avoids having "real versioning" and maintaining old versions etc.
To be honest, this is more of a mindset topic: Introducing "real versioning" to me has the risk of thinking less about how stable APIs and avoiding breaking changes works...

**Comment by yae-leanix** [comment]
@perbernhardt and @superquadratic Thanks for the great input, I really like the idea of the feature branch :) I will add the remaining functionality, including the rollback mode and rename this branch for easier checkouts.

**Comment by yae-leanix** [comment]
Better branch name and labeled as breaking change: https://github.com/leanix/storage-deploy-action/pull/12

**Pull request closed without merging**
