### PR TITLE
CLN-4295 Enable providing a storage account prefix

### PR DESCRIPTION
**Pull request by konstantintieber**
The cleanshelf storage accounts start with "si".

This parameter is required so that they can start using the storage-deploy-action too.

Requested by @mplesec for the SMP team :)

### CODE REVIEW

**Comment by konstantintieber** [comment]
@yae-leanix would appreciate to hear your opinion on this implementation for supporting prefixes other than leanix.

**Comment by konstantintieber** [comment]
And just now I realized something I'd like to ask @mplesec: Why can't you use the leanix storage account as well?

Was this a decision by team hook that the two accounts are separate?

**Comment by yae-leanix** [comment]
I think the implementation is totally fine.
With respect to this action being open source, the new parameter is obviously a good idea :) I think we can merge it without problems.

**Review by yae-leanix — APPROVED** [review]

**Comment by yae-leanix** [comment]
> Was this a decision by team hook that the two accounts are separate?

@konstantintieber to me it seems that this is a question of ownership. All Azure resources that we use for the EAM and VSM products fall under the LeanIX Production subscription.
Probably (I am only assuming based on observations), it was decided by Team Hook that it is a good idea to separate the resources required by SMP from the resource required to run EAM and VSM. I would not argue against this decision. To have one cloud provider subscription per product, seems sensible to me.

**Comment by konstantintieber** [comment]
Thanks a lot for your always thought through input @yae-leanix 🙏

**Pull request merged**
