### PR TITLE
THRST-344 Minimise Partial Upload Errors

### PR DESCRIPTION
**Pull request by yae-leanix**
- Minimise chunk load errors by first uploading the release in an extra folder and then moving the files into the root directory as a second step

⚠️ Chunk errors are often caused by customers accessing partially uploaded files (for example fingerprinted files that are not changed or files without fingerprints).

### CODE REVIEW

**Comment by konstantintieber** [comment]
TODO: delete `nextRelease` folder contents after copying its contents to the root of the cdn container.

**Comment by konstantintieber** [comment]
I've started a deployment to test-app-kot-1.leanix.net using this branch here: https://github.com/leanix/leanix-pathfinder-web/runs/3007233541

**Comment by konstantintieber** [comment]
Rerun of deployment with changes from https://github.com/leanix/storage-deploy-action/pull/19/commits/64413859242c69ebd222383b88fd441467554f9b: https://github.com/leanix/leanix-pathfinder-web/runs/3007707951

**Comment by yae-leanix** [comment]
It seems `azcopy` only supports asynchronous copying of files. So even if you copy from some file share to the same file share, `azcopy` will do this over HTTP. 
The conclusion is: Using `azcopy` we cannot quickly get what we want to do in this PR and probably we cannot do it at all as long as we are using Azure File Share. So the remaining alternative is again to look into fingerprinting files.

**Comment by konstantintieber** [comment]
Thank you for investigating and documenting this 🚀

**Pull request closed without merging**
