### PR TITLE
HOOK-3730 Introduce retry logic for request throttling

### PR DESCRIPTION
**Pull request by dan-leanix**
According to yesterday's introduced logging we are running into the request throttling.

-> https://leanix.slack.com/archives/CAFCKMBFH/p1638457207299700?thread_ts=1637576920.199300&cid=CAFCKMBFH

So, does this makes sense to you having those kind of retry logic?

### CODE REVIEW

**Review by perbernhardt — COMMENTED** [review]
I wonder whether we have a conceptual flow that makes us call the "list storage account" resource too often. If I read https://stackoverflow.com/questions/45849519/throttling-issue-while-listing-azure-storage-accounts correctly, then we do that more than 100 times per 5 minutes.
So for example: Do we really need to test for the storage account explicitly? If it would not be there, then e.g. the "azcopy" would just fail, perhaps giving a less readable error message... But then again: How often do we suffer from using the wrong storageAccount name accidentally?

**Comment by dan-leanix** [comment]
We are running into 

Storage account management operations (read) | 800 per 5 minutes
-- | --

Storage account management operations (list) | 100 per 5 minutes
-- | --

I mean we can skip the listing of the account and the check for the container. But I don't know if `azcopy` automatically creates a container on an existing storage account which in the end will collide with our IaC approach.

**Comment by dan-leanix** [comment]
@perbernhardt From my perspective we can reduce it here https://github.com/leanix/storage-deploy-action/blob/master/index.js#L139 to only one call the `az storage container exists`. If the storage account does not exist, we would also get an error and would cover two cases:

1. Storage Account does not exist
2. Container does not exist

**Comment by perbernhardt** [comment]
> @perbernhardt From my perspective we can reduce it here https://github.com/leanix/storage-deploy-action/blob/master/index.js#L139 to only one call the `az storage container exists`. If the storage account does not exist, we would also get an error and would cover two cases:
> 
> 1. Storage Account does not exist
> 2. Container does not exist

Yes exactly, we could at least do that!

I also tried to find documentation on whether azcopy would create a container "on the fly". So there is an explicit command for that ("azcopy make [CONTAINER]"), but I am not sure whether the normal "azcopy cp" would also do that. Perhaps we can quickly try that out?

**Comment by dan-leanix** [comment]
> I also tried to find documentation on whether azcopy would create a container "on the fly". So there is an explicit command for that ("azcopy make [CONTAINER]"), but I am not sure whether the normal "azcopy cp" would also do that. Perhaps we can quickly try that out?

Will try it out today.

**Review by konstantintieber — APPROVED** [review]
Even if we end up doing something else, your retry mechanism code looks good to me.

Thanks a lot for your super valuable contributions.

**Comment by dan-leanix** [comment]
@perbernhardt Here the result from an `azcopy sync` command when the storage container does not exists:

```bash
azcopy sync istio/ https://leanixwesteuropetest.blob.core.windows.net/dantest/ --recursive --delete-destination false
INFO: Authenticating to destination using Azure AD
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 27a2f0c0-4429-1b40-6676-6d2ff3512fd5 has started
Log file is located at: /Users/danielneumann/.azcopy/27a2f0c0-4429-1b40-6676-6d2ff3512fd5.log

0 Files Scanned at Source, 0 Files Scanned at Destination
Cannot perform sync due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.13.1-0.20210823171415-e7932f52ad61/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=ContainerNotFound) =====
Description=The specified container does not exist.
RequestId:660c71b8-501e-0046-1f43-e8ce6b000000
Time:2021-12-03T12:41:12.4868965Z, Details:
   Code: ContainerNotFound
   GET https://leanixwesteuropetest.blob.core.windows.net/dantest?comp=list&delimiter=%2F&include=metadata&restype=container&timeout=901
   Authorization: REDACTED
   User-Agent: [AzCopy/10.13.0 Azure-Storage/0.14 (go1.17.2; darwin)]
   X-Ms-Client-Request-Id: [c557d2f7-c3c3-4de8-4e32-8b5b6ea76f3b]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified container does not exist.
   Access-Control-Allow-Origin: [*]
   Access-Control-Expose-Headers: [x-ms-request-id,x-ms-client-request-id,Server,x-ms-version,x-ms-error-code,Content-Length,Date,Transfer-Encoding]
   Content-Length: [225]
   Content-Type: [application/xml]
   Date: [Fri, 03 Dec 2021 12:41:11 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [c557d2f7-c3c3-4de8-4e32-8b5b6ea76f3b]
   X-Ms-Error-Code: [ContainerNotFound]
   X-Ms-Request-Id: [660c71b8-501e-0046-1f43-e8ce6b000000]
   X-Ms-Version: [2019-12-12]
```

**Comment by dan-leanix** [comment]
@perbernhardt But we need a check on the storage account, because otherwise the `az storage container exists` retries 3 times if the storage account does not exist which will waste every time a storage account does not exists 60 seconds.

`azcopy` also retries for me in the end forever if the storage account does not exist.

Hence, the conclusion would be to merge the PR with the retry logic and observe if we improve the `storage-deploy-action` execution.

**Review by perbernhardt — APPROVED** [review]
@dan-leanix Understood and agreed! 👍

**Comment by dan-leanix** [comment]
@perbernhardt @konstantintieber Great and thanks! I will merge it on Monday morning.

**Review by perbernhardt — COMMENTED** [review]
Hi @dan-leanix , sorry to open up this one again, but I finally noticed, what the flow is here:
We completely optimise for the wrong situation here.

So in ALMOST ALL OF THE CASES (like 99,99%, I just don't have a figure...) this storage-deploy-action is correctly configured for an existing account & container. Only if e.g. a new workflow is setup before the container was created by service-environment, let's say for a new microfrontend, then this action might be used with a "missing container".

So if we look on the normal use case: It is totally ok to get rid of all the storage & container lookups, because azcopy will just work if they are there! We will save tons of lookup calls on the API and also not run into the ratelimit (not only here but perhaps also in other processes).

If we look on the broken use case (new service/missing container): Then yes, directly running azcopy might idle forever or only give an error after some minutes, but this is completely correct and ok! We would also have quite a slow experience here if we add the proposed retry. One can also manually cancel the workspace etc.

So with all of this I am back again to: Get rid of all the lookups and just directly use azcopy 😞

**Comment by dan-leanix** [comment]
@perbernhardt No worries. I will make the necessary adjustments today.

**Comment by dan-leanix** [comment]
@perbernhardt @konstantintieber Please, review again. Thanks!

**Review by konstantintieber — APPROVED** [review]
I love it when code can be removed.

Thanks so much @perbernhardt and @dan-leanix

**Review by perbernhardt — APPROVED** [review]
LGTM, thanks @dan-leanix !

**Pull request merged**
